# Generated by Django 5.0.1 on 2024-03-06 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_shippingaddress_zipcode_alter_shippingaddress_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="zipCode",
            new_name="zipcode",
        ),
    ]
